# From https://gist.github.com/peetw/10f49281423753d068f62bf47ba4642f
#
# - This dockerfile may need to be run more than once until it builds successfully.
#
# This Dockerfile sets up a PostgreSQL 9.6 server
# Adapted from: https://github.com/StefanScherer/dockerfiles-windows/blob/master/postgres/Dockerfile
FROM microsoft/windowsservercore@sha256:c06b4bfaf634215ea194e6005450740f3a230b27c510cf8facab1e9c678f3a99

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN [Net.ServicePointManager]::SecurityProtocol = 'Tls12, Tls11, Tls' ; \
    Invoke-WebRequest -UseBasicParsing -Uri 'https://get.enterprisedb.com/postgresql/postgresql-9.6.10-2-windows-x64.exe' -OutFile 'postgresql-installer.exe' ; \
    Start-Process postgresql-installer.exe -ArgumentList '--mode unattended --superpassword password' -Wait ; \
    Remove-Item postgresql-installer.exe -Force

RUN Invoke-WebRequest -UseBasicParsing -Uri 'https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.3/ServiceMonitor.exe' -OutFile 'ServiceMonitor.exe'

SHELL ["cmd", "/S", "/C"]

RUN setx /M PATH "C:\\Program Files\\PostgreSQL\\9.6\\bin;%PATH%" && \
    setx /M DATA_DIR "C:\\Program Files\\PostgreSQL\\9.6\\data" && \
    setx /M PGPASSWORD "password"

RUN powershell -Command "Do { pg_isready -q } Until ($?)" && \
    echo listen_addresses = '*' >> "%DATA_DIR%\\postgresql.conf" && \
    echo host  all  all  0.0.0.0/0  trust >> "%DATA_DIR%\\pg_hba.conf" && \
    echo host  all  all  ::0/0      trust >> "%DATA_DIR%\\pg_hba.conf" && \
    net stop postgresql-x64-9.6

EXPOSE 5432

CMD ["ServiceMonitor.exe", "postgresql-x64-9.6"]
